services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:nightly-25598999a2b33ac6ccfa35c347f3c98aba8e0061
    ports: ["8545:8545"]
    entrypoint:
      [
        "anvil",
        "--fork-url",
        "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
        "--host",
        "0.0.0.0",
        "--silent",
        "--hardfork",
        "prague",
      ]
    platform: linux/x86_64

  mock-paymaster:
    restart: always
    depends_on:
      - anvil
    image: ghcr.io/pimlicolabs/mock-verifying-paymaster:main
    ports: ["3000:3000"]
    environment:
      - ALTO_RPC=http://alto:4337
      - ANVIL_RPC=http://anvil:8545

  alto:
    depends_on:
      - anvil
    image: ghcr.io/pimlicolabs/mock-alto-bundler:main
    ports: ["4337:4337"]
    environment:
      - ANVIL_RPC=http://anvil:8545
      - SKIP_DEPLOYMENTS=true
